### ISSUE TITLE
PRINTL命令里面没法放%VAR:a%

### ISSUE THREAD

**Issue by Junyi-99** [Lyt99/Fork#1]
比如：
COLOR Green
PRINTL 喵！
COLOR Gray
COLOR Yellow
PRINTL ಠ౪ಠ 你是谁？
COLOR Gray
INPUT name
COLOR Green
PRINT _(┐「ε:)_  哦哦，原来是%LOCAL:name%
PRINTVARS %LOCAL:name%
PRINTL 啊，幸会幸会！
COLOR Gray

**Comment by Lyt99** [comment]
设计如此< <
