### ISSUE TITLE
建议：提供LIST命令，而不是LISTADD

### ISSUE THREAD

**Issue by Junyi-99** [Lyt99/Fork#10]
比如我想声明一个LIST而不是往里面加数据。
LISTADD a 屠龙宝刀
LISTADD a 屠龙宝刀
LISTADD a 金疮药
LISTADD a 屠龙宝刀
LISTADD a 金疮药
LISTADD a 屠龙宝刀
LISTADD a 灵巧披风
LISTADD a 屠龙宝刀
LISTADD b
PRINTL 原始LIST:
COLOR Green
FOR i a
	PRINTVARS %LOCAL:i%
	PRINTL 
	SETVAR now_num 0
	FOR j b
		IF "%LOCAL:i%" == "%LOCAL:j%"
			SETVAR now_num 1
		ENDIF
	ENDFOR
	IF %VAR:now_num% == 0
		LISTADD b %LOCAL:i%
	;如果b列表没有当前物品，那么向B列表添加当前物品
	ENDIF
ENDFOR
COLOR Gray

PRINTL 去重操作
COLOR Cyan
FOR i b
	PRINTVARS %LOCAL:i%
	PRINTL 
ENDFOR
COLOR Gray
EXIT

如果我不LISTADD b，那我就没法FOR j b。
然而我LISTADD b之后，这个LIST的首项是个空的元素。

虽然我可以LISTADD b NULL，让第一项一直为NULL，
但感觉挺麻烦的，第二个FOR i b 还要去除第一个元素（不让第一个元素输出）

**Comment by Military-Doctor** [comment]
`LISTADD a 屠龙宝刀
LISTADD a 屠龙宝刀
LISTADD a 金疮药
LISTADD a 屠龙宝刀
LISTADD a 金疮药
LISTADD a 屠龙宝刀
LISTADD a 灵巧披风
LISTADD a 屠龙宝刀
LISTADD b
PRINTL 原始LIST:
COLOR Green
FOR i a
	PRINTVARS %LOCAL:i%
	PRINTL 
	SETVAR now_num 0
	FOR j b
		IF "%LOCAL:i%" == "%LOCAL:j%"
			SETVAR now_num 1
		ENDIF
	ENDFOR
	IF %VAR:now_num% == 0
		LISTADD b %LOCAL:i%
	;如果b列表没有当前物品，那么向B列表添加当前物品
	ENDIF
ENDFOR
COLOR Gray

PRINTL 去重操作
COLOR Cyan
FOR i b
	PRINTVARS %LOCAL:i%
	PRINTL 
ENDFOR
COLOR Gray
EXIT`

**Comment by Junyi-99** [comment]
![image](https://cloud.githubusercontent.com/assets/14367694/22635413/8760e832-ec6e-11e6-8451-61e8d1e1fd36.png)

**Comment by Lyt99** [comment]
已修复
