### ISSUE TITLE
BUG：关于ADDCMD的

### ISSUE THREAD

**Issue by Junyi-99** [Lyt99/Fork#12]
ADDCMD help.zs -h
如果help.zs不存在，就会崩
ProjectFork.Exceptions.ScriptNotFoundException: File/Folder: Command/help.zs not found.
   在 ProjectFork.Scripter.GetScriptFile(String filename) 位置 C:\Users\Junyi\Documents\V
isual Studio 2015\Projects\Fork\ProjectUnknown\Scripter.cs:行号 91
   在 ProjectFork.Commander.RunCommand(String cmdwithpars) 位置 C:\Users\Junyi\Documents\
Visual Studio 2015\Projects\Fork\ProjectUnknown\Commander.cs:行号 62
   在 ProjectFork.Commander.Start() 位置 C:\Users\Junyi\Documents\Visual Studio 2015\Proj
ects\Fork\ProjectUnknown\Commander.cs:行号 83
   在 ProjectFork.Program.Main(String[] args) 位置 C:\Users\Junyi\Documents\Visual Studio
 2015\Projects\Fork\ProjectUnknown\Program.cs:行号 20

**Comment by Lyt99** [comment]
设计如此……
