### ISSUE TITLE
我发现脚本并不是实时解析的

### ISSUE THREAD

**Issue by Junyi-99** [Lyt99/Fork#3]
比如我运行了个ProjectFork.exe，然后我输入了Meow，在不结束ProjectFork.exe的情况下我修改了Mewo的脚本命令，又输入了Meow。
它还是执行原来的脚本。
就是说，我在不结束当前进程的情况下，对外部脚本的修改不会影响到当前程序的执行。。

**Comment by Lyt99** [comment]
设计如此，真的< <
