### ISSUE TITLE
如果有一行字符串内容是 \t

### ISSUE THREAD

**Issue by Junyi-99** [Lyt99/Fork#5]
我的脚本：
COLOR Green
PRINTL 喵！
COLOR Gray
COLOR Yellow
PRINTL ಠ౪ಠ 你是谁？
COLOR Gray
INPUT name
COLOR Green
PRINT Meow > _(┐「ε:)_ 哇，原来是
PRINTVARS %LOCAL:name%
PRINTL 啊，幸会幸会！
COLOR Gray
SLEEP 0.1
COLOR Green
PRINT Meow > 嗯
SLEEP 0.1
PRINT .
SLEEP 0.1
PRINT .
SLEEP 0.1
PRINTL .
SLEEP 1
PRINTVARS %LOCAL:name%
PRINTL 你找我有什么事儿吗？
COLOR #00D4FF
PRINTL 1.没什么事儿 \t 2.我想学习膜法
PRINTL 3.我昨晚吃多了 \t 4.你知道山东省实验中学怎么走吗
COLOR Gray
PRINTVARS %LOCAL:name% 
INPUT event
COLOR Green
SWITCH %LOCAL:event%
	CASE 1
		PRINTL 哦，再见！
	CASE 2
		PRINTL 哦，再见！
	CASE 3
		PRINTL 哦，再见！
	CASE 4
		PRINTL 哦，再见！
		
	DEFAULT
		PRINTL wwwwwwwwa
ENDSWITCH

=====================================================

ProjectFork.Exceptions.ParserException: Can't parse: at line 41.
   在 ProjectFork.Helper.CreateScriptLine(String line, Int32& e, ScriptFile script) 位置
C:\Users\Junyi\Documents\Visual Studio 2015\Projects\Fork\ProjectUnknown\Helper.cs:行号 2
6
   在 ProjectFork.ScriptLines.SWITCH.Process(String line, Int32& e, ScriptFile script) 位
置 C:\Users\Junyi\Documents\Visual Studio 2015\Projects\Fork\ProjectUnknown\ScriptLines\S WITCH.cs:行号 48
   在 ProjectFork.Helper.CreateScriptLine(String line, Int32& e, ScriptFile script) 位置
C:\Users\Junyi\Documents\Visual Studio 2015\Projects\Fork\ProjectUnknown\Helper.cs:行号 1
05
   在 ProjectFork.ScriptFile.Reload() 位置 C:\Users\Junyi\Documents\Visual Studio 2015\Pr
ojects\Fork\ProjectUnknown\ScriptFile.cs:行号 92
   在 ProjectFork.ScriptFile..ctor(String file) 位置 C:\Users\Junyi\Documents\Visual Stud
io 2015\Projects\Fork\ProjectUnknown\ScriptFile.cs:行号 70
   在 ProjectFork.Scripter.Load() 位置 C:\Users\Junyi\Documents\Visual Studio 2015\Projec
ts\Fork\ProjectUnknown\Scripter.cs:行号 57
   在 ProjectFork.Program.Main(String[] args) 位置 C:\Users\Junyi\Documents\Visual Studio
 2015\Projects\Fork\ProjectUnknown\Program.cs:行号 18

**Comment by Lyt99** [comment]
是因为DEFAULT前的空行导致的，不是Tab的事儿，总之，已修复
