### ISSUE TITLE
建议：添加随机数命令

### ISSUE THREAD

**Issue by Junyi-99** [Lyt99/Fork#8]
预定一些对话，然后随机输出。
比如：
> anofi
Meow: 你说的是啥？
> ana2
Meow: 我听不懂哎！
> c0za2
Meow: ？？？

**Comment by Junyi-99** [comment]
也可以用随机命令实现随机扣血、随机爆装备之类的功能

**Comment by Lyt99** [comment]
随机数有一个变量为%RANDOM%，可以生成0-100的随机数，正在找更好的处理方法
