### ISSUE TITLE
BUG：强行让一个LOCAL变量等于一个LIST

### ISSUE THREAD

**Issue by Junyi-99** [Lyt99/Fork#9]
![default](https://cloud.githubusercontent.com/assets/14367694/22635170/1528a7fc-ec6c-11e6-9189-2762dd4ca437.png)
)

**Comment by Military-Doctor** [comment]
改成 i == j 也是出错
==================================

原始LIST
屠龙宝刀
ProjectFork.Exceptions.RuntimeException: i == j is not a Boolean value
   在 ProjectFork.ScriptLines.IF.Run(FConsole console) 位置 C:\Users\Junyi\Documents\Visu
al Studio 2015\Projects\Fork\ProjectUnknown\ScriptLines\IF.cs:行号 56
   在 ProjectFork.ScriptLines.FOR.Run(FConsole console) 位置 C:\Users\Junyi\Documents\Vis
ual Studio 2015\Projects\Fork\ProjectUnknown\ScriptLines\FOR.cs:行号 76
   在 ProjectFork.ScriptLines.FOR.Run(FConsole console) 位置 C:\Users\Junyi\Documents\Vis
ual Studio 2015\Projects\Fork\ProjectUnknown\ScriptLines\FOR.cs:行号 76
   在 ProjectFork.ScriptFile.Run(FConsole console) 位置 C:\Users\Junyi\Documents\Visual S
tudio 2015\Projects\Fork\ProjectUnknown\ScriptFile.cs:行号 103
   在 ProjectFork.Commander.RunCommand(String cmdwithpars) 位置 C:\Users\Junyi\Documents\
Visual Studio 2015\Projects\Fork\ProjectUnknown\Commander.cs:行号 71
   在 ProjectFork.Commander.Start() 位置 C:\Users\Junyi\Documents\Visual Studio 2015\Proj
ects\Fork\ProjectUnknown\Commander.cs:行号 83
   在 ProjectFork.Program.Main(String[] args) 位置 C:\Users\Junyi\Documents\Visual Studio
 2015\Projects\Fork\ProjectUnknown\Program.cs:行号 20
==================================

**Comment by Junyi-99** [comment]
`
LISTADD a 屠龙宝刀
LISTADD a 屠龙宝刀
LISTADD a 金疮药
LISTADD a 屠龙宝刀
LISTADD a 金疮药
LISTADD a 屠龙宝刀
LISTADD a 灵巧披风
LISTADD a 屠龙宝刀
LISTADD b NULL
LISTADD c NULL
PRINTL 原始LIST
FOR i a
	PRINTVARS %LOCAL:i%
	PRINTL 
	FOR j b
		IF i == j
			SETVAR now_num = now_num + 1
		ENDIF
	ENDFOR
	IF now_num == 0
		LISTADD b i ;如果b列表没有当前物品，那么向B列表添加当前物品
	ENDIF
ENDFOR
PRINTL 去重操作
FOR i b
	PRINTVARS %LOCAL:i%
	PRINTL 
ENDFOR

EXIT
`

**Comment by Junyi-99** [comment]
我知道为啥了，忘了写%LOCAL:%了
